# Generated by Django 5.2.5 on 2025-08-31 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileConversionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("ppt_to_pdf", "PPT转PDF"),
                            ("doc_to_pdf", "DOC转PDF"),
                            ("xls_to_pdf", "XLS转PDF"),
                        ],
                        max_length=20,
                        verbose_name="转换类型",
                    ),
                ),
                ("source_directory", models.CharField(max_length=500, verbose_name="源目录")),
                ("output_directory", models.CharField(max_length=500, verbose_name="输出目录")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                ("total_files", models.IntegerField(default=0, verbose_name="总文件数")),
                ("processed_files", models.IntegerField(default=0, verbose_name="已处理文件数")),
                ("success_files", models.IntegerField(default=0, verbose_name="成功文件数")),
                ("failed_files", models.IntegerField(default=0, verbose_name="失败文件数")),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件转换任务",
                "verbose_name_plural": "文件转换任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="toolbox.fileconversiontask",
                        verbose_name="任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "转换日志",
                "verbose_name_plural": "转换日志",
                "ordering": ["-created_at"],
            },
        ),
    ]
