# Generated by Django 4.2.20 on 2025-04-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="branches",
        ),
        migrations.AddField(
            model_name="repository",
            name="_branches",
            field=models.JSONField(
                db_column="branches", default=list, help_text="仓库的所有分支列表"
            ),
        ),
        migrations.AlterField(
            model_name="globalconfig",
            name="repo_base_dir",
            field=models.CharField(
                default="~/jobs",
                help_text="仓库克隆的基础目录，默认为 ~/jobs",
                max_length=255,
            ),
        ),
    ]
