# Generated by Django 5.2.5 on 2025-08-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0005_alter_repository__branches_alter_repository_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeTypeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "class_identifier",
                    models.CharField(
                        help_text="班级标识，如班级名称或路径", max_length=255, unique=True
                    ),
                ),
                (
                    "grade_type",
                    models.CharField(
                        choices=[
                            ("letter", "字母等级 (A/B/C/D/E)"),
                            ("text", "文本等级 (优秀/良好/中等/及格/不及格)"),
                            ("numeric", "数字等级 (90-100/80-89/70-79/60-69/0-59)"),
                        ],
                        default="letter",
                        help_text="评分类型",
                        max_length=20,
                    ),
                ),
                ("is_locked", models.BooleanField(default=False, help_text="是否已锁定评分类型")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "评分类型配置",
                "verbose_name_plural": "评分类型配置",
                "db_table": "grading_grade_type_config",
            },
        ),
    ]
