# Generated by Django 5.2.5 on 2025-08-12 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0006_gradetypeconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="租户名称", max_length=100, unique=True)),
                ("description", models.TextField(blank=True, help_text="租户描述")),
                ("is_active", models.BooleanField(default=True, help_text="是否激活")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "租户",
                "verbose_name_plural": "租户",
                "db_table": "grading_tenant",
            },
        ),
        migrations.AlterModelOptions(
            name="repository",
            options={"verbose_name": "仓库", "verbose_name_plural": "仓库"},
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={"verbose_name": "提交", "verbose_name_plural": "提交"},
        ),
        migrations.RemoveField(
            model_name="globalconfig",
            name="https_password",
        ),
        migrations.RemoveField(
            model_name="globalconfig",
            name="https_username",
        ),
        migrations.RemoveField(
            model_name="globalconfig",
            name="repo_base_dir",
        ),
        migrations.RemoveField(
            model_name="globalconfig",
            name="ssh_key",
        ),
        migrations.RemoveField(
            model_name="globalconfig",
            name="ssh_key_file",
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="description",
            field=models.TextField(blank=True, default="默认仓库基础目录", help_text="配置描述"),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="key",
            field=models.CharField(
                default="default_repo_base_dir", help_text="配置键", max_length=100, unique=True
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="value",
            field=models.TextField(default="~/jobs", help_text="配置值"),
        ),
        migrations.AddField(
            model_name="repository",
            name="description",
            field=models.TextField(blank=True, help_text="仓库描述"),
        ),
        migrations.AddField(
            model_name="repository",
            name="is_active",
            field=models.BooleanField(default=True, help_text="是否激活"),
        ),
        migrations.AddField(
            model_name="repository",
            name="path",
            field=models.CharField(default="", help_text="仓库路径", max_length=500),
        ),
        migrations.AddField(
            model_name="submission",
            name="comment",
            field=models.TextField(blank=True, help_text="评语"),
        ),
        migrations.AddField(
            model_name="submission",
            name="file_name",
            field=models.CharField(
                default=django.utils.timezone.now, help_text="文件名", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="file_path",
            field=models.CharField(
                default=django.utils.timezone.now, help_text="文件路径", max_length=500
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="file_size",
            field=models.BigIntegerField(default=0, help_text="文件大小"),
        ),
        migrations.AddField(
            model_name="submission",
            name="graded_at",
            field=models.DateTimeField(blank=True, help_text="评分时间", null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="grading.repository",
            ),
        ),
        migrations.AlterField(
            model_name="gradetypeconfig",
            name="class_identifier",
            field=models.CharField(help_text="班级标识，如班级名称或路径", max_length=255),
        ),
        migrations.AlterField(
            model_name="repository",
            name="name",
            field=models.CharField(help_text="仓库名称", max_length=255),
        ),
        migrations.AlterField(
            model_name="submission",
            name="grade",
            field=models.CharField(blank=True, default="A", help_text="评分", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, help_text="提交时间"),
        ),
        migrations.AlterModelTable(
            name="globalconfig",
            table="grading_global_config",
        ),
        migrations.AlterModelTable(
            name="repository",
            table="grading_repository",
        ),
        migrations.AlterModelTable(
            name="submission",
            table="grading_submission",
        ),
        migrations.AlterUniqueTogether(
            name="repository",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="gradetypeconfig",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_type_configs",
                to="grading.tenant",
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repositories",
                to="grading.tenant",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="grading.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gradetypeconfig",
            unique_together={("tenant", "class_identifier")},
        ),
        migrations.AlterUniqueTogether(
            name="repository",
            unique_together={("tenant", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("tenant", "repository", "file_path")},
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "repo_base_dir",
                    models.CharField(blank=True, help_text="用户基础仓库目录", max_length=500),
                ),
                (
                    "is_tenant_admin",
                    models.BooleanField(default=False, help_text="是否为租户管理员"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="所属租户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="grading.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户配置文件",
                "verbose_name_plural": "用户配置文件",
                "db_table": "grading_user_profile",
            },
        ),
        migrations.RemoveField(
            model_name="repository",
            name="_branches",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="last_sync_time",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="url",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="repository_url",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="status",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="student",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="teacher_comments",
        ),
        migrations.CreateModel(
            name="TenantConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(help_text="配置键", max_length=100)),
                ("value", models.TextField(help_text="配置值")),
                ("description", models.TextField(blank=True, help_text="配置描述")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to="grading.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "租户配置",
                "verbose_name_plural": "租户配置",
                "db_table": "grading_tenant_config",
                "unique_together": {("tenant", "key")},
            },
        ),
    ]
