# Generated by Django 5.2.5 on 2025-08-27 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0007_tenant_alter_repository_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="学期名称，如：2024年春季学期", max_length=100),
                ),
                ("start_date", models.DateField(help_text="学期第一周第一天上课日期")),
                ("end_date", models.DateField(help_text="学期结束日期")),
                ("is_active", models.BooleanField(default=True, help_text="是否为当前学期")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "学期",
                "verbose_name_plural": "学期",
                "db_table": "grading_semester",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="课程名称", max_length=200)),
                ("description", models.TextField(blank=True, help_text="课程描述")),
                ("location", models.CharField(help_text="上课地点", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="授课教师",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        help_text="所属学期",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="grading.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "db_table": "grading_course",
                "ordering": ["semester", "name"],
            },
        ),
        migrations.CreateModel(
            name="CourseSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "周一"),
                            (2, "周二"),
                            (3, "周三"),
                            (4, "周四"),
                            (5, "周五"),
                            (6, "周六"),
                            (7, "周日"),
                        ],
                        help_text="星期几",
                    ),
                ),
                (
                    "period",
                    models.IntegerField(
                        choices=[
                            (1, "第一大节 (8:00-9:40)"),
                            (2, "第二大节 (10:00-11:40)"),
                            (3, "第三大节 (14:00-15:40)"),
                            (4, "第四大节 (16:00-17:40)"),
                            (5, "第五大节 (19:00-20:40)"),
                        ],
                        help_text="第几大节",
                    ),
                ),
                ("start_week", models.IntegerField(help_text="开始周次")),
                ("end_week", models.IntegerField(help_text="结束周次")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        help_text="课程",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="grading.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程安排",
                "verbose_name_plural": "课程安排",
                "db_table": "grading_course_schedule",
                "ordering": ["weekday", "period"],
                "unique_together": {("course", "weekday", "period")},
            },
        ),
    ]
