# Generated by Django 5.2.5 on 2025-08-27 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0008_semester_course_courseschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="class_name",
            field=models.CharField(
                blank=True, help_text="班级名称，如：计算机科学1班", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="CourseWeekSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("week_number", models.IntegerField(help_text="周次")),
                ("is_active", models.BooleanField(default=True, help_text="是否在该周上课")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_schedule",
                    models.ForeignKey(
                        help_text="课程安排",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_schedules",
                        to="grading.courseschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程周次安排",
                "verbose_name_plural": "课程周次安排",
                "db_table": "grading_course_week_schedule",
                "ordering": ["week_number"],
                "unique_together": {("course_schedule", "week_number")},
            },
        ),
    ]
