# Generated by Django 4.2.20 on 2025-11-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0010_alter_courseweekschedule_unique_together_and_more'),
        ('grading', '0013_add_semester_template_model'),
    ]

    operations = [
    ]
