# Generated by Django 4.2.20 on 2025-11-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0024_course_tenant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['course', 'tenant'], name='grading_cla_course__e2468b_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher', 'semester'], name='grading_cou_teacher_ca7235_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['tenant', 'semester'], name='grading_cou_tenant__cbcaf3_idx'),
        ),
        migrations.AddIndex(
            model_name='gradetypeconfig',
            index=models.Index(fields=['tenant', 'class_obj'], name='grading_gra_tenant__d8676a_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['course', 'folder_name'], name='grading_hom_course__2975ca_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['tenant', 'homework_type'], name='grading_hom_tenant__dfde73_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['owner', 'is_active'], name='grading_rep_owner_i_a0a6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['tenant', 'is_active'], name='grading_rep_tenant__70046b_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['class_obj', 'is_active'], name='grading_rep_class_o_a7fd72_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['repo_type', 'is_active'], name='grading_rep_repo_ty_c6626f_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['repository', '-submitted_at'], name='grading_sub_reposit_eec2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['tenant', '-submitted_at'], name='grading_sub_tenant__941fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', '-submitted_at'], name='grading_sub_student_cbaefe_idx'),
        ),
    ]
