# Generated by Django 4.2.20 on 2025-12-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0027_add_assignment_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="git_url",
            field=models.CharField(
                blank=True,
                help_text="Git仓库URL（支持 http://, https://, git://, ssh://, git@ 格式）",
                max_length=500,
                null=True,
            ),
        ),
    ]
