# Generated by Django 4.2.19 on 2025-03-16 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('url', models.URLField(max_length=255, verbose_name='仓库地址')),
                ('branch', models.CharField(default='main', max_length=100, verbose_name='分支')),
                ('local_path', models.CharField(max_length=255, verbose_name='本地路径')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='密码')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '作业仓库',
                'verbose_name_plural': '作业仓库',
                'ordering': ['-created_at'],
            },
        ),
    ]
