# Generated by Django 4.2.19 on 2025-03-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='ssh_key',
            field=models.TextField(blank=True, help_text='仅 SSH 协议需要', null=True, verbose_name='SSH 私钥'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='password',
            field=models.CharField(blank=True, help_text='仅 HTTPS 协议需要', max_length=100, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(help_text='支持 HTTPS 和 SSH 协议', max_length=255, verbose_name='仓库地址'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='username',
            field=models.CharField(blank=True, help_text='仅 HTTPS 协议需要', max_length=100, null=True, verbose_name='用户名'),
        ),
    ]
