# Generated by Django 4.2.20 on 2025-07-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0002_remove_repository_branches_repository__branches_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="teacher_comments",
            field=models.TextField(blank=True, null=True, verbose_name="教师评价"),
        ),
    ]
