# Generated by Django 4.2.19 on 2025-03-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_repository_ssh_key_alter_repository_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('https_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='HTTPS 用户名')),
                ('https_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='HTTPS 密码')),
                ('ssh_key', models.TextField(blank=True, null=True, verbose_name='SSH 私钥')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '全局配置',
                'verbose_name_plural': '全局配置',
            },
        ),
        migrations.RemoveField(
            model_name='repository',
            name='password',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='ssh_key',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='username',
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='仓库名称'),
        ),
    ]
