# Generated by Django 4.2.19 on 2025-03-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_globalconfig_remove_repository_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='ssh_key_file',
            field=models.FileField(blank=True, help_text='上传 SSH 私钥文件', null=True, upload_to='ssh_keys/', verbose_name='SSH 私钥文件'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='ssh_key',
            field=models.TextField(blank=True, help_text='SSH 私钥内容', null=True, verbose_name='SSH 私钥'),
        ),
    ]
