# Generated by Django 5.2.5 on 2025-08-08 10:47

from django.conf import settings
from django.db import migrations, models

import grading.models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0004_repository_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="_branches",
            field=models.JSONField(
                db_column="branches",
                default=grading.models.get_default_branches,
                help_text="仓库的所有分支列表",
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="repository",
            unique_together={("name", "owner")},
        ),
    ]
