# Generated by Django 4.2.19 on 2025-03-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_globalconfig_ssh_key_file_alter_globalconfig_ssh_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='ssh_key_file',
            field=models.FileField(blank=True, help_text='上传 SSH 私钥文件，支持所有标准的私钥文件格式', null=True, upload_to='ssh_keys/', verbose_name='SSH 私钥文件'),
        ),
    ]
