# Generated by Django 4.2.16 on 2025-03-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0006_alter_globalconfig_ssh_key_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['-updated_at'], 'verbose_name': '仓库', 'verbose_name_plural': '仓库'},
        ),
        migrations.RemoveField(
            model_name='repository',
            name='last_sync',
        ),
        migrations.AddField(
            model_name='repository',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='https_password',
            field=models.CharField(blank=True, help_text='HTTPS 克隆时使用的密码', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='https_username',
            field=models.CharField(blank=True, help_text='HTTPS 克隆时使用的用户名', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='ssh_key',
            field=models.TextField(blank=True, help_text='SSH 克隆时使用的私钥内容', null=True),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='ssh_key_file',
            field=models.FileField(blank=True, help_text='SSH 私钥文件', null=True, upload_to='ssh_keys/'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='branch',
            field=models.CharField(default='main', max_length=100),
        ),
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='local_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.URLField(),
        ),
    ]
