# Generated by Django 4.2.16 on 2025-03-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0007_alter_repository_options_remove_repository_last_sync_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(help_text='支持 SSH 和 HTTPS 格式。SSH 格式示例：git@gitee.com:username/repository.git，HTTPS 格式示例：https://gitee.com/username/repository.git', max_length=255),
        ),
    ]
