# Generated by Django 4.2.16 on 2025-03-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0008_alter_repository_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='repo_base_dir',
            field=models.CharField(default='media/repo', help_text='仓库克隆的基础目录', max_length=255),
        ),
    ]
