# Generated by Django 5.2.5 on 2025-09-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0004_repository_owner"),
        ("grading", "0009_course_class_name_courseweekschedule"),
    ]

    operations = []
