# Generated by Django 4.2.20 on 2025-10-26 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grading.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("grading", "0009_course_class_name_courseweekschedule"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courseweekschedule",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="courseweekschedule",
            name="course_schedule",
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "提交",
                "verbose_name_plural": "提交",
            },
        ),
        migrations.AlterUniqueTogether(
            name="repository",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="repo_base_dir",
        ),
        migrations.AddField(
            model_name="assignment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="所属租户",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="grading.tenant",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="所属租户",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="grading.tenant",
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="_branches",
            field=models.JSONField(
                db_column="branches",
                default=grading.models.get_default_branches,
                help_text="仓库的所有分支列表",
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="branch",
            field=models.CharField(default="main", max_length=255),
        ),
        migrations.AddField(
            model_name="repository",
            name="last_sync_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="仓库所有者",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="url",
            field=models.CharField(blank=True, default="", help_text="仓库URL", max_length=255),
        ),
        migrations.AddField(
            model_name="semester",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="所属租户",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters",
                to="grading.tenant",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="所属租户",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="grading.tenant",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="grading.assignment",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="repository_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待评分"),
                    ("graded", "已评分"),
                    ("late", "逾期提交"),
                    ("failed", "未通过"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="grading.student",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="teacher_comments",
            field=models.TextField(blank=True, null=True, verbose_name="教师评价"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="tenant_repo_dir",
            field=models.CharField(
                default="", help_text="租户仓库目录（相对于全局基础目录）", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="class_name",
            field=models.CharField(default="", help_text="班级名称", max_length=100),
        ),
        migrations.AlterField(
            model_name="globalconfig",
            name="description",
            field=models.TextField(blank=True, help_text="配置描述"),
        ),
        migrations.AlterField(
            model_name="globalconfig",
            name="key",
            field=models.CharField(help_text="配置键", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="globalconfig",
            name="value",
            field=models.TextField(help_text="配置值"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="repository",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="所属租户",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repositories",
                to="grading.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file_name",
            field=models.CharField(default="", help_text="文件名", max_length=255),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file_path",
            field=models.CharField(default="", help_text="文件路径", max_length=500),
        ),
        migrations.AlterField(
            model_name="submission",
            name="grade",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="所属租户",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="grading.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("tenant", "semester", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="repository",
            unique_together={("tenant", "url")},
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("tenant", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("tenant", "student_id")},
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("tenant", "student", "assignment")},
        ),
        migrations.DeleteModel(
            name="CourseSchedule",
        ),
        migrations.DeleteModel(
            name="CourseWeekSchedule",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="path",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="comment",
        ),
    ]
