# Generated by Django 5.2.5 on 2025-09-27 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0011_add_repository_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="auto_created",
            field=models.BooleanField(default=False, help_text="是否为自动创建"),
        ),
        migrations.AddField(
            model_name="semester",
            name="reference_semester",
            field=models.ForeignKey(
                blank=True,
                help_text="参考学期（用于自动创建）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="grading.semester",
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="season",
            field=models.CharField(
                blank=True,
                choices=[("spring", "春季"), ("autumn", "秋季")],
                help_text="学期季节",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="owner",
            field=models.ForeignKey(
                help_text="仓库所有者",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repositories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="is_active",
            field=models.BooleanField(default=False, help_text="是否为当前学期"),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                fields=("start_date", "end_date"), name="unique_semester_period"
            ),
        ),
    ]
