# Generated by Django 5.2.5 on 2025-09-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0012_add_semester_auto_creation_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SemesterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[("spring", "春季"), ("autumn", "秋季")],
                        help_text="学期季节",
                        max_length=10,
                    ),
                ),
                ("start_month", models.IntegerField(help_text="开始月份 (1-12)")),
                ("start_day", models.IntegerField(help_text="开始日期 (1-31)")),
                ("end_month", models.IntegerField(help_text="结束月份 (1-12)")),
                ("end_day", models.IntegerField(help_text="结束日期 (1-31)")),
                ("duration_weeks", models.IntegerField(default=16, help_text="学期周数")),
                (
                    "name_pattern",
                    models.CharField(
                        default="{year}年{season}",
                        help_text="命名模式，如'{year}年{season}'",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="是否启用此模板")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "学期模板",
                "verbose_name_plural": "学期模板",
                "db_table": "grading_semester_template",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("season",),
                        name="unique_active_season_template",
                    )
                ],
            },
        ),
    ]
