# Generated by Django 4.2.20 on 2025-11-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0020_add_userprofile_repo_base_dir"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={"verbose_name": "提交", "verbose_name_plural": "提交"},
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="_branches",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="last_sync_time",
        ),
        migrations.AddField(
            model_name="repository",
            name="path",
            field=models.CharField(default="", help_text="仓库路径", max_length=500),
        ),
        migrations.AddField(
            model_name="submission",
            name="comment",
            field=models.TextField(blank=True, default="", help_text="评语"),
        ),
        migrations.AlterField(
            model_name="course",
            name="class_name",
            field=models.CharField(
                blank=True, help_text="班级名称，如：计算机科学1班", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="globalconfig",
            name="description",
            field=models.TextField(
                blank=True, default="默认仓库基础目录", help_text="配置描述"
            ),
        ),
        migrations.AlterField(
            model_name="globalconfig",
            name="key",
            field=models.CharField(
                default="default_repo_base_dir",
                help_text="配置键",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="globalconfig",
            name="value",
            field=models.TextField(default="~/jobs", help_text="配置值"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="branch",
            field=models.CharField(
                default="main", help_text="默认分支", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="name",
            field=models.CharField(help_text="仓库名称", max_length=255),
        ),
        migrations.AlterField(
            model_name="repository",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repositories",
                to="grading.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="url",
            field=models.URLField(blank=True, help_text="仓库URL（Git仓库）"),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file_name",
            field=models.CharField(help_text="文件名", max_length=255),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file_path",
            field=models.CharField(help_text="文件路径", max_length=500),
        ),
        migrations.AlterField(
            model_name="submission",
            name="grade",
            field=models.CharField(
                blank=True, default="", help_text="评分", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="grading.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="repo_base_dir",
            field=models.CharField(
                blank=True, help_text="用户基础仓库目录", max_length=500
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("tenant", "repository", "file_path")},
        ),
        migrations.CreateModel(
            name="CourseSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "周一"),
                            (2, "周二"),
                            (3, "周三"),
                            (4, "周四"),
                            (5, "周五"),
                            (6, "周六"),
                            (7, "周日"),
                        ],
                        help_text="星期几",
                    ),
                ),
                (
                    "period",
                    models.IntegerField(
                        choices=[
                            (1, "第一大节 (8:00-9:40)"),
                            (2, "第二大节 (10:00-11:40)"),
                            (3, "第三大节 (14:00-15:40)"),
                            (4, "第四大节 (16:00-17:40)"),
                            (5, "第五大节 (19:00-20:40)"),
                        ],
                        help_text="第几大节",
                    ),
                ),
                ("start_week", models.IntegerField(help_text="开始周次")),
                ("end_week", models.IntegerField(help_text="结束周次")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        help_text="课程",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="grading.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程安排",
                "verbose_name_plural": "课程安排",
                "db_table": "grading_course_schedule",
                "ordering": ["weekday", "period"],
                "unique_together": {("course", "weekday", "period")},
            },
        ),
        migrations.RemoveField(
            model_name="course",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="semester",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="student",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="repository_url",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="status",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="student",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="teacher_comments",
        ),
        migrations.CreateModel(
            name="CourseWeekSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField(help_text="周次")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="是否在该周上课"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_schedule",
                    models.ForeignKey(
                        help_text="课程安排",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_schedules",
                        to="grading.courseschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程周次安排",
                "verbose_name_plural": "课程周次安排",
                "db_table": "grading_course_week_schedule",
                "ordering": ["week_number"],
                "unique_together": {("course_schedule", "week_number")},
            },
        ),
    ]
