# Generated by Django 4.2.20 on 2025-11-30 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grading', '0022_fix_missing_tenant_repo_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='班级名称', max_length=200)),
                ('student_count', models.IntegerField(default=0, help_text='学生人数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 'grading_class',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('personal', '个人模板'), ('system', '系统模板')], help_text='模板类型', max_length=20)),
                ('comment_text', models.TextField(help_text='评价内容')),
                ('usage_count', models.IntegerField(default=0, help_text='使用次数')),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='最后使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '评价模板',
                'verbose_name_plural': '评价模板',
                'db_table': 'grading_comment_template',
                'ordering': ['-usage_count', '-last_used_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at'], 'verbose_name': '提交', 'verbose_name_plural': '提交'},
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        # Note: Course.tenant already exists from migration 0007, skipping
        migrations.AddField(
            model_name='homework',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='所属租户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='grading.tenant'),
        ),
        migrations.AddField(
            model_name='repository',
            name='allocated_space_mb',
            field=models.IntegerField(default=1024, help_text='分配空间（MB）'),
        ),
        migrations.AddField(
            model_name='repository',
            name='filesystem_path',
            field=models.CharField(blank=True, help_text='文件系统路径', max_length=500),
        ),
        migrations.AddField(
            model_name='repository',
            name='git_branch',
            field=models.CharField(blank=True, default='main', help_text='Git分支', max_length=100),
        ),
        migrations.AddField(
            model_name='repository',
            name='git_password',
            field=models.CharField(blank=True, help_text='Git密码（加密存储）', max_length=200),
        ),
        migrations.AddField(
            model_name='repository',
            name='git_url',
            field=models.URLField(blank=True, help_text='Git仓库URL', null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='git_username',
            field=models.CharField(blank=True, help_text='Git用户名', max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='homework',
            field=models.ForeignKey(blank=True, help_text='所属作业', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='grading.homework'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(blank=True, help_text='提交学生', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='version',
            field=models.IntegerField(default=1, help_text='版本号'),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, help_text='上课地点', max_length=100),
        ),
        migrations.AlterField(
            model_name='gradetypeconfig',
            name='class_identifier',
            field=models.CharField(blank=True, help_text='班级标识，如班级名称或路径（兼容旧版本）', max_length=255),
        ),
        migrations.AlterField(
            model_name='gradetypeconfig',
            name='grade_type',
            field=models.CharField(choices=[('letter', '字母等级 (A/B/C/D/E)'), ('text', '文本等级 (优秀/良好/中等/及格/不及格)'), ('percentage', '百分制 (0-100)')], default='letter', help_text='评分类型', max_length=20),
        ),
        migrations.AlterField(
            model_name='gradetypeconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='所属租户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_type_configs', to='grading.tenant'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='branch',
            field=models.CharField(default='main', help_text='默认分支（兼容旧版本）', max_length=100),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repo_type',
            field=models.CharField(choices=[('git', 'Git仓库'), ('filesystem', '文件系统')], default='filesystem', help_text='仓库类型', max_length=20),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.URLField(blank=True, help_text='仓库URL（兼容旧版本）'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file_name',
            field=models.CharField(help_text='文件名', max_length=200),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file_size',
            field=models.IntegerField(default=0, help_text='文件大小（字节）'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='repository',
            field=models.ForeignKey(blank=True, help_text='所属仓库', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='grading.repository'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='所属租户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='grading.tenant'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['homework', 'student', '-submitted_at'], name='grading_sub_homewor_27ae80_idx'),
        ),
        migrations.AddField(
            model_name='commenttemplate',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='教师（个人模板有teacher）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commenttemplate',
            name='tenant',
            field=models.ForeignKey(help_text='所属租户', on_delete=django.db.models.deletion.CASCADE, related_name='comment_templates', to='grading.tenant'),
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(help_text='所属课程', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='grading.course'),
        ),
        migrations.AddField(
            model_name='class',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='所属租户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='grading.tenant'),
        ),
        migrations.AddField(
            model_name='gradetypeconfig',
            name='class_obj',
            field=models.ForeignKey(blank=True, help_text='关联班级', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_type_configs', to='grading.class'),
        ),
        migrations.AddField(
            model_name='homework',
            name='class_obj',
            field=models.ForeignKey(blank=True, help_text='所属班级', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='grading.class'),
        ),
        migrations.AddField(
            model_name='repository',
            name='class_obj',
            field=models.ForeignKey(blank=True, help_text='关联班级', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='grading.class'),
        ),
        migrations.AddIndex(
            model_name='commenttemplate',
            index=models.Index(fields=['teacher', 'template_type', '-usage_count'], name='grading_com_teacher_725d54_idx'),
        ),
        migrations.AddIndex(
            model_name='commenttemplate',
            index=models.Index(fields=['tenant', 'template_type', '-usage_count'], name='grading_com_tenant__6d6cbf_idx'),
        ),
    ]
