# Generated by Django 4.2.20 on 2025-11-30 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0023_update_models_for_homework_grading_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='所属租户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='grading.tenant'),
        ),
    ]
